import { TestCase } from './planner';

export function validateTestCases(testCases: TestCase[]): void {
  if (!Array.isArray(testCases) || testCases.length === 0) {
    throw new Error('No test cases generated by Planner.');
  }

  testCases.forEach((tc, index) => {
    if (!tc.testName) {
      throw new Error(`Test case at index ${index} has no testName.`);
    }

    if (!tc.steps || tc.steps.length === 0) {
      throw new Error(`Test case "${tc.testName}" has no steps.`);
    }

    const step = tc.steps[0].toLowerCase();

    if (
      !step.includes('valid') &&
      !step.includes('invalid') &&
      !step.includes('empty')
    ) {
      console.warn(
        `⚠️ Warning: "${tc.testName}" contains unmapped step: "${tc.steps[0]}"`
      );
    }
  });

  console.log('Validation successful.');
}